---
- name: Zabbix Web Dashboard
  docker_container:
    name: "{{ zabbix_web_container_name }}"
    image: "{{ zabbix_web_image }}"
    state: started
    restart: yes
    recreate: yes
    restart_policy: unless-stopped
    links:
      - "{{ mysql_container_name }}:mysql"
      - "{{ zabbix_server_container_name }}:zabbix-server"
    ports:
      - "{{ zabbix_exp_ports }}"
    env:
      DB_SERVER_HOST: "{{ zabbix_server_db_host }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      PHP_TZ: "{{ zabbix_web_php_tz }}"