{
 "title": "SSL Check",
 "description": "Check days of certificate expire",
 "tags": [ "SSL" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Group",
    "label": "Group",
    "query": {}
   },
   {
    "name": "Domain",
    "label": "Domain",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Digital Certificate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SSL certificate" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Domain" },
     "item": { "filter": "/HTTPS/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Issuer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "application": { "filter": "SSL certificate" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Domain" },
     "item": { "filter": "/SSL certificate issuer/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Domain",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "application": { "filter": "SSL certificate" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Domain" },
     "item": { "filter": "/validity/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Response time for step",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "application": { "filter": "SSL certificate" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Domain" },
     "item": { "filter": "/Response time for step/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Download speed for scenario",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "SSL certificate" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Domain" },
     "item": { "filter": "/Download speed for scenario/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}