{
 "title": "Zabbix - Microsoft IIS",
 "tags": [ "Windows" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Group",
    "label": "Group",
    "query": {}
   },
   {
    "name": "Host",
    "label": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "IIS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Zabbix agent" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Host name of zabbix_agentd running"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "World Side Web Publishing Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "IIS" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "World Side Web Publishing Service"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Remote Desktop Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Services" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Remote Desktop Services" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "IIS" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Service Uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "IIS Data Transfer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Bytes Received/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Data Transfer" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Bytes Received/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bytes Sent/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Data Transfer" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Bytes Sent/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bytes Total/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "decbytes", "label": "2" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Data Transfer" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Bytes Total/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "IIS Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Locked Errors/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Errors" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Locked Errors/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Not Found Errors/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Errors" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Not Found Errors/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "IIS Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Requests/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Requests" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Requests/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Get Requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Requests" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Get Requests/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Post Requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Requests" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Post Requests/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Put Requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Requests" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Put Requests/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Delete Requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "IIS Requests" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Delete Requests/sec" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}